/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AddCandidatePayload = IDL.Record({
  'name' : IDL.Text,
  'party' : IDL.Text,
  'photo' : ExternalBlob,
});
export const CandidateId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VoterId = IDL.Text;
export const VoteResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Record({ 'message' : IDL.Text }),
});
export const CandidateInfo = IDL.Record({
  'id' : CandidateId,
  'voteCount' : IDL.Nat,
  'name' : IDL.Text,
  'party' : IDL.Text,
  'photo' : ExternalBlob,
});
export const ElectionStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const ElectionResults = IDL.Record({
  'totalVotes' : IDL.Nat,
  'electionStatus' : ElectionStatus,
  'candidates' : IDL.Vec(CandidateInfo),
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text }),
  'err' : IDL.Record({ 'message' : IDL.Text }),
});
export const RegisterResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Record({ 'message' : IDL.Text }),
});
export const UpdateCandidatePayload = IDL.Record({
  'id' : CandidateId,
  'name' : IDL.Text,
  'party' : IDL.Text,
  'photo' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCandidate' : IDL.Func([AddCandidatePayload], [CandidateId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([VoterId, CandidateId], [VoteResult], []),
  'deleteCandidate' : IDL.Func([CandidateId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidates' : IDL.Func([], [IDL.Vec(CandidateInfo)], ['query']),
  'getElectionStatus' : IDL.Func([], [ElectionStatus], ['query']),
  'getResults' : IDL.Func([], [ElectionResults], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([VoterId, IDL.Text], [LoginResult], []),
  'registerVoter' : IDL.Func(
      [VoterId, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
  'setElectionStatus' : IDL.Func([ElectionStatus], [], []),
  'updateCandidate' : IDL.Func([UpdateCandidatePayload], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AddCandidatePayload = IDL.Record({
    'name' : IDL.Text,
    'party' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const CandidateId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VoterId = IDL.Text;
  const VoteResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IDL.Record({ 'message' : IDL.Text }),
  });
  const CandidateInfo = IDL.Record({
    'id' : CandidateId,
    'voteCount' : IDL.Nat,
    'name' : IDL.Text,
    'party' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const ElectionStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
  });
  const ElectionResults = IDL.Record({
    'totalVotes' : IDL.Nat,
    'electionStatus' : ElectionStatus,
    'candidates' : IDL.Vec(CandidateInfo),
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text }),
    'err' : IDL.Record({ 'message' : IDL.Text }),
  });
  const RegisterResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IDL.Record({ 'message' : IDL.Text }),
  });
  const UpdateCandidatePayload = IDL.Record({
    'id' : CandidateId,
    'name' : IDL.Text,
    'party' : IDL.Text,
    'photo' : ExternalBlob,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCandidate' : IDL.Func([AddCandidatePayload], [CandidateId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func([VoterId, CandidateId], [VoteResult], []),
    'deleteCandidate' : IDL.Func([CandidateId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidates' : IDL.Func([], [IDL.Vec(CandidateInfo)], ['query']),
    'getElectionStatus' : IDL.Func([], [ElectionStatus], ['query']),
    'getResults' : IDL.Func([], [ElectionResults], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([VoterId, IDL.Text], [LoginResult], []),
    'registerVoter' : IDL.Func(
        [VoterId, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
    'setElectionStatus' : IDL.Func([ElectionStatus], [], []),
    'updateCandidate' : IDL.Func([UpdateCandidatePayload], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };