/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddCandidatePayload {
  'name' : string,
  'party' : string,
  'photo' : ExternalBlob,
}
export type CandidateId = bigint;
export interface CandidateInfo {
  'id' : CandidateId,
  'voteCount' : bigint,
  'name' : string,
  'party' : string,
  'photo' : ExternalBlob,
}
export interface ElectionResults {
  'totalVotes' : bigint,
  'electionStatus' : ElectionStatus,
  'candidates' : Array<CandidateInfo>,
}
export type ElectionStatus = { 'closed' : null } |
  { 'open' : null };
export type ExternalBlob = Uint8Array;
export type LoginResult = { 'ok' : { 'token' : string } } |
  { 'err' : { 'message' : string } };
export type RegisterResult = { 'ok' : null } |
  { 'err' : { 'message' : string } };
export interface UpdateCandidatePayload {
  'id' : CandidateId,
  'name' : string,
  'party' : string,
  'photo' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoteResult = { 'ok' : null } |
  { 'err' : { 'message' : string } };
export type VoterId = string;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCandidate' : ActorMethod<[AddCandidatePayload], CandidateId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[VoterId, CandidateId], VoteResult>,
  'deleteCandidate' : ActorMethod<[CandidateId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidates' : ActorMethod<[], Array<CandidateInfo>>,
  'getElectionStatus' : ActorMethod<[], ElectionStatus>,
  'getResults' : ActorMethod<[], ElectionResults>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[VoterId, string], LoginResult>,
  'registerVoter' : ActorMethod<[VoterId, string, string], RegisterResult>,
  'setElectionStatus' : ActorMethod<[ElectionStatus], undefined>,
  'updateCandidate' : ActorMethod<[UpdateCandidatePayload], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];