/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type VoteResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: {
        message: string;
    };
};
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ElectionResults {
    totalVotes: bigint;
    electionStatus: ElectionStatus;
    candidates: Array<CandidateInfo>;
}
export interface CandidateInfo {
    id: CandidateId;
    voteCount: bigint;
    name: string;
    party: string;
    photo: ExternalBlob;
}
export interface AddCandidatePayload {
    name: string;
    party: string;
    photo: ExternalBlob;
}
export type VoterId = string;
export interface UpdateCandidatePayload {
    id: CandidateId;
    name: string;
    party: string;
    photo: ExternalBlob;
}
export type RegisterResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: {
        message: string;
    };
};
export type CandidateId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type LoginResult = {
    __kind__: "ok";
    ok: {
        token: string;
    };
} | {
    __kind__: "err";
    err: {
        message: string;
    };
};
export enum ElectionStatus {
    closed = "closed",
    open = "open"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addCandidate(payload: AddCandidatePayload): Promise<CandidateId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    castVote(ghanaCardId: VoterId, candidateId: CandidateId): Promise<VoteResult>;
    deleteCandidate(id: CandidateId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidates(): Promise<Array<CandidateInfo>>;
    getElectionStatus(): Promise<ElectionStatus>;
    getResults(): Promise<ElectionResults>;
    isCallerAdmin(): Promise<boolean>;
    login(ghanaCardId: VoterId, passwordHash: string): Promise<LoginResult>;
    registerVoter(ghanaCardId: VoterId, phone: string, passwordHash: string): Promise<RegisterResult>;
    setElectionStatus(status: ElectionStatus): Promise<void>;
    updateCandidate(payload: UpdateCandidatePayload): Promise<boolean>;
}
import type { AddCandidatePayload as _AddCandidatePayload, CandidateId as _CandidateId, CandidateInfo as _CandidateInfo, ElectionResults as _ElectionResults, ElectionStatus as _ElectionStatus, ExternalBlob as _ExternalBlob, LoginResult as _LoginResult, RegisterResult as _RegisterResult, UpdateCandidatePayload as _UpdateCandidatePayload, UserRole as _UserRole, VoteResult as _VoteResult, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCandidate(arg0: AddCandidatePayload): Promise<CandidateId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCandidate(await to_candid_AddCandidatePayload_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCandidate(await to_candid_AddCandidatePayload_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async castVote(arg0: VoterId, arg1: CandidateId): Promise<VoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0, arg1);
                return from_candid_VoteResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0, arg1);
            return from_candid_VoteResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCandidate(arg0: CandidateId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCandidate(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidates(): Promise<Array<CandidateInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidates();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidates();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getElectionStatus(): Promise<ElectionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getElectionStatus();
                return from_candid_ElectionStatus_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElectionStatus();
            return from_candid_ElectionStatus_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResults(): Promise<ElectionResults> {
        if (this.processError) {
            try {
                const result = await this.actor.getResults();
                return from_candid_ElectionResults_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResults();
            return from_candid_ElectionResults_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: VoterId, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerVoter(arg0: VoterId, arg1: string, arg2: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVoter(arg0, arg1, arg2);
                return from_candid_RegisterResult_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVoter(arg0, arg1, arg2);
            return from_candid_RegisterResult_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async setElectionStatus(arg0: ElectionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setElectionStatus(to_candid_ElectionStatus_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setElectionStatus(to_candid_ElectionStatus_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCandidate(arg0: UpdateCandidatePayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(await to_candid_UpdateCandidatePayload_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(await to_candid_UpdateCandidatePayload_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_CandidateInfo_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandidateInfo): Promise<CandidateInfo> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ElectionResults_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElectionResults): Promise<ElectionResults> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ElectionStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElectionStatus): ElectionStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LoginResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_VoteResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteResult): VoteResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CandidateId;
    voteCount: bigint;
    name: string;
    party: string;
    photo: _ExternalBlob;
}): Promise<{
    id: CandidateId;
    voteCount: bigint;
    name: string;
    party: string;
    photo: ExternalBlob;
}> {
    return {
        id: value.id,
        voteCount: value.voteCount,
        name: value.name,
        party: value.party,
        photo: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.photo)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalVotes: bigint;
    electionStatus: _ElectionStatus;
    candidates: Array<_CandidateInfo>;
}): Promise<{
    totalVotes: bigint;
    electionStatus: ElectionStatus;
    candidates: Array<CandidateInfo>;
}> {
    return {
        totalVotes: value.totalVotes,
        electionStatus: from_candid_ElectionStatus_n21(_uploadFile, _downloadFile, value.electionStatus),
        candidates: await from_candid_vec_n17(_uploadFile, _downloadFile, value.candidates)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: {
        message: string;
    };
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: {
        message: string;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): ElectionStatus {
    return "closed" in value ? ElectionStatus.closed : "open" in value ? ElectionStatus.open : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
    };
} | {
    err: {
        message: string;
    };
}): {
    __kind__: "ok";
    ok: {
        token: string;
    };
} | {
    __kind__: "err";
    err: {
        message: string;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CandidateInfo>): Promise<Array<CandidateInfo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CandidateInfo_n18(_uploadFile, _downloadFile, x)));
}
async function to_candid_AddCandidatePayload_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddCandidatePayload): Promise<_AddCandidatePayload> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ElectionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElectionStatus): _ElectionStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UpdateCandidatePayload_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCandidatePayload): Promise<_UpdateCandidatePayload> {
    return await to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CandidateId;
    name: string;
    party: string;
    photo: ExternalBlob;
}): Promise<{
    id: _CandidateId;
    name: string;
    party: string;
    photo: _ExternalBlob;
}> {
    return {
        id: value.id,
        name: value.name,
        party: value.party,
        photo: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photo)
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    party: string;
    photo: ExternalBlob;
}): Promise<{
    name: string;
    party: string;
    photo: _ExternalBlob;
}> {
    return {
        name: value.name,
        party: value.party,
        photo: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photo)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ElectionStatus): {
    closed: null;
} | {
    open: null;
} {
    return value == ElectionStatus.closed ? {
        closed: null
    } : value == ElectionStatus.open ? {
        open: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
